export const DATA_UPDATE = 'DATA_UPDATE';
export const FILTER_DATA_UPDATE = 'FILTER_DATA_UPDATE';
export const FAVOURITES_DATA_UPDATE = 'FAVOURITES_DATA_UPDATE';
export const MORE_UPDATE = 'MORE_UPDATE';
